### ISSUE TITLE
很想看WebSocket聊天室的源码

### ISSUE THREAD

**Issue by jiangkai-rq** [FireNio/firenio#56]
老铁，我很想看一下WebSocket聊天室的代码，能share一下嘛

**Comment by wangkaish** [comment]
代码在这里： https://github.com/FireNio/firenio/blob/master/firenio-sample/sample-http/src/main/java/sample/http11/service/TestWebSocketChatServlet.java
https://github.com/FireNio/firenio/blob/master/firenio-sample/sample-http/src/main/java/sample/http11/service/WebSocketMsgAdapter.java

**Comment by jiangkai-rq** [comment]
老铁，你是在上海吗？可以聊一下吗，我也在上海

**Comment by wangkaish** [comment]
@jiangkai-rq 我在上海可以给我发邮件 wangkaicloud@163.com
